dist: trusty
language: perl
perl:
  - "5.20"
addons:
  postgresql: 9.5
env:
  global:
    - SL_HOST=127.0.0.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-server-dev-all postgresql-contrib
  - psql -c "CREATE USER vagrant WITH PASSWORD 'password'" -U postgres
  - psql -c "CREATE DATABASE scrabblicious OWNER=vagrant" -U postgres
  - psql -c "CREATE EXTENSION IF NOT EXISTS pgcrypto" scrabblicious -U postgres
  - cp -a $TRAVIS_BUILD_DIR/scrabblicious.sample.conf $TRAVIS_BUILD_DIR/scrabblicious.development.conf
  - cp -a $TRAVIS_BUILD_DIR/scrabblicious.sample.conf $TRAVIS_BUILD_DIR/scrabblicious.production.conf
  - cp -a $TRAVIS_BUILD_DIR/migrations/scrabblicious.sql /tmp/scrabblicious.sql
  - PGPASSWORD=password psql -U vagrant -h localhost scrabblicious < /tmp/scrabblicious.sql
install:
  - cpanm -n Carton
  - carton install --deployment --cached
script:
  - carton exec prove -rl
after_failure: "cat ~/.cpanm/build.log"
notifications:
  email: true
