#!/usr/bin/env perl

use strict;
use warnings;
use DBIx::Class::Schema::Loader qw/make_schema_at/;
use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

# Added result_base_class on recommendation from the cookbook to improve
# startup speed. Not necessarily a big deal at the moment, but as a schema
# grows and when developing, it will be a help.
#
# Additionally it makes it easier to load new components without rebuilding the
# schema.
#
# http://search.cpan.org/~ribasushi/DBIx-Class-0.08250/lib/DBIx/Class/Manual/Cookbook.pod#STARTUP_SPEED

# postgres => scrabblicious
make_schema_at(
  'Scrabblicious::Schema',
  {
    db_schema               => 'public',
    relationships           => 1,
    dump_directory          => "$FindBin::Bin/../lib",
    debug                   => 1,
    result_base_class       => 'Scrabblicious::Schema::BaseResult',
  },
  [
    'dbi:Pg:dbname=scrabblicious;host=' . ($ENV{SL_HOST} // 'localhost'),
    'postgres', ''
  ],
);
